name: Deploy Aether Mail on Release

on:
  release:
    types: [published]  # Se déclenche uniquement lors de la publication d'une release

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Aether Mail to webmail.skygenesisenterprise.com and Mobile Platforms
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout Aether Mail repository
        uses: actions/checkout@v4

      # Étape 2 : Déployer sur le serveur webmail.skygenesisenterprise.com via FTP
      - name: Upload Aether Mail to webmail.skygenesisenterprise.com
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER_WEBMAIL }}
          password: ${{ secrets.FTP_PASS_WEBMAIL }}
          local-dir: ./  # Répertoire local à déployer
          server-dir: /www/  # Répertoire distant sur le serveur

      # Étape 3 : Préparer le build pour Android
      - name: Build Android APK
        run: |
          echo "Building Android APK..."
          ./gradlew assembleRelease
        working-directory: ./android

      # Étape 4 : Publier sur Google Play Store
      - name: Deploy to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.skygenesis.aethermail
          releaseFiles: ./android/app/build/outputs/apk/release/app-release.apk
          track: production
          status: completed

      # Étape 5 : Préparer le build pour iOS
      - name: Build iOS App
        run: |
          echo "Building iOS App..."
          xcodebuild -workspace AetherMail.xcworkspace -scheme AetherMail -sdk iphoneos -configuration AppStoreDistribution archive -archivePath ./build/AetherMail.xcarchive
        working-directory: ./ios

      # Étape 6 : Publier sur l'App Store via Fastlane
      - name: Deploy to Apple App Store
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: "appstore"  # Nom de la lane Fastlane pour publier
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
          APP_STORE_CONNECT_API_ISSUER: ${{ secrets.APP_STORE_API_ISSUER }}