name: Mark stale issues and PRs
permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been inactive for 30 days. If there is no further activity, it will be closed in 7 days.
          stale-pr-message: >
            This pull request has been inactive for 30 days. If there is no update, it will be closed in 7 days.
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'pinned,security,discussion'
          exempt-pr-labels: 'pinned,do-not-close'
